directories:
  output: release
  buildResources: build
appId: com.apitestingtool.app
productName: API Testing Tool
files:
  - filter:
      - build/**/*
      - dist/main.js
      - node_modules/**/*
mac:
  category: public.app-category.developer-tools
win:
  target: nsis
electronVersion: 25.9.8
